pipeline {
    agent {label 'swarm-devops'}

    stages {
        stage('Prepare') {
            steps {
		echo 'Verificar git..'
		checkout scm
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
		echo "BUILD NUMBER: ${env.BUILD_NUMBER}"
		sh "hostname"
		sh "pwd"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
