pipeline {
	agent {
		// Equivalent to "docker build -f Dockerfile.build --build-arg version=1.0.2 ./build/
		dockerfile {
		filename 'Dockerfile'
		dir 'nginx'
		label 'swarm-devops'
		additionalBuildArgs  "-t webmolona:0.0.${env.BUILD_NUMBER}"
		}
	}
	stages {
		stage('Test') {
			steps {
				echo 'Testing..'
				echo "BUILD NUMBER: ${env.BUILD_NUMBER}"
				sh "hostname"
				sh "pwd"
				sh "cd docker"
				sh "ls -la"
			}
		}
	}
}
